# Generated by Django 3.1.4 on 2021-02-15 23:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_subpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(form_classname='title', required=False)), ('paragraph', wagtail.core.blocks.TextBlock(form_classname='full')), ('rich', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'ul', 'ol', 'bold', 'italic', 'link', 'hr'], form_classname='full'))]),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.core.blocks.TextBlock(form_classname='full')), ('rich', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'ul', 'ol', 'bold', 'italic', 'link', 'hr'], form_classname='full')), ('images', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())], icon='image'))]),
        ),
    ]
