# Generated by Django 3.1.7 on 2021-03-07 23:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_change_streamfield_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(form_classname='title', icon='title')), ('paragraph', wagtail.core.blocks.TextBlock(form_classname='full')), ('rich', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'ul', 'ol', 'bold', 'italic', 'link', 'hr'], form_classname='full')), ('images', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())], icon='image')), ('video', wagtail.embeds.blocks.EmbedBlock(help_text='Paste in link to the video to be embedded at this spot. For example: https://vimeo.com/517009861'))]),
        ),
    ]
