# Generated by Django 3.1.7 on 2021-04-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_map_n_signup_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappage',
            name='icon',
            field=models.CharField(default='fa-info-circle', max_length=30, verbose_name='Menu Icon'),
        ),
        migrations.AddField(
            model_name='signuppage',
            name='icon',
            field=models.CharField(default='fa-info-circle', max_length=30, verbose_name='Menu Icon'),
        ),
        migrations.AddField(
            model_name='subpage',
            name='icon',
            field=models.CharField(default='fa-info-circle', max_length=30, verbose_name='Menu Icon'),
        ),
    ]
