# Generated by Django 3.1.8 on 2021-08-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_reference_first_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streetsignup.city'),
        ),
    ]
