# Generated by Django 3.1.8 on 2021-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_homepage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='attribution',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
