# Generated by Django 3.1.14 on 2022-05-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_add_map_center_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='event_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
