# Generated by Django 3.1 on 2020-08-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('church', models.CharField(max_length=40)),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streetsignup.street')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(db_index=True, unique=True)),
                ('path', models.JSONField()),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetsignup.street')),
            ],
        ),
    ]
