# Generated by Django 3.1.1 on 2020-09-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='streetsignup.street'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streetsignup.street'),
        ),
    ]
