# Generated by Django 3.1.1 on 2020-09-20 21:06

from django.db import migrations


def move_flags(apps, schema_editor):
    # We can't import the Subscription model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Subscription = apps.get_model('streetsignup', 'Subscription')
    Contact = apps.get_model('streetsignup', 'Contact')
    for sub in Subscription.objects.all():
        contacts = Contact.objects.filter(email=sub.email)
        if not contacts.exists():
            contact = Contact(name=sub.name, email=sub.email)
        else:
            contact = contacts.first()

        if sub.verified:
            contact.verified = True
        if sub.unsubscribed:
            contact.unsubscribed = True

        contact.save()
        sub.contact = contact
        sub.save()


def move_flags_back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0005_contact'),
    ]

    operations = [
        migrations.RunPython(move_flags, move_flags_back),
    ]
