# Generated by Django 3.1.1 on 2020-09-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0006_move_flags_to_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='unsubscribed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='verified',
        ),
    ]
