# Generated by Django 3.1.1 on 2020-09-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0007_remove_flag_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ask_consent_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='streetsignup.contact'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='streetsignup.street'),
        ),
    ]
