# Generated by Django 3.1.4 on 2021-01-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0008_add_email_sent_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='objectid',
        ),
    ]
