# Generated by Django 3.1.7 on 2021-03-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0009_remove_segment_objectid'),
    ]

    operations = [
        migrations.AlterField(   # If this line fails replace 'AlterField' with 'AddField'
            model_name='segment',
            name='objectid',
            field=models.IntegerField(null=True),
        ),
    ]
