# Generated by Django 3.2.6 on 2021-08-05 05:10

from django.db import migrations, models

# def move_flags(apps, schema_editor):
#     # We can't import the Subscription model directly as it may be a newer
#     # version than this migration expects. We use the historical version.
#     City = apps.get_model('streetsignup', 'City')
#     Street = apps.get_model('streetsignup', 'Street')
#



class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0010_make_objectid_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=80)),
                ('site', models.CharField(max_length=80)),
            ],
        ),
        # migrations.RunPython(move_flags, move_flags_back),
    ]
