# Generated by Django 3.2.6 on 2021-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0010_make_objectid_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=80)),
                ('site', models.CharField(max_length=80)),
            ],
        ),
    ]
