# Generated by Django 3.2.6 on 2021-08-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0011_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='city_site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='streetsignup.city'),
            preserve_default=False,
        ),
    ]
