# Generated by Django 3.2.6 on 2021-08-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0012_street_city_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
