# Generated by Django 3.1.8 on 2021-08-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0014_add_first_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='city_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetsignup.city'),
        ),
    ]
