# Generated by Django 3.1.8 on 2021-08-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetsignup', '0015_city_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='site',
        ),
    ]
