# Generated by Django 3.1.8 on 2021-08-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('streetsignup', '0016_remove_city_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
